### ISSUE TITLE
mailto: e-mail address & title is not set correctly

### ISSUE THREAD

**Issue by dominikgeissler** [sbsev/site#94] opened 2023-01-25 12:52 UTC
Reproduction steps:
1. Select any chapter
2. Click on the link
![image](https://user-images.githubusercontent.com/39053640/214568004-be5ce1b3-d051-4f87-b68a-488662959912.png)
3. Results in
![image2](https://user-images.githubusercontent.com/39053640/214568121-ebecd27d-d19a-44a9-823e-d9bff44671b6.png)

***
cf. Ticket #113

**Comment by janosh** [comment] 2023-01-25 15:55
@dominikgeissler Good catch! This has been broken since Jun 24 2022 when I merged https://github.com/sbsev/site/pull/52 (commit 4e5a6873cd8fc0a6c929745e818faca91cd3c92a). In that PR @kleinicke reworked the chapter pages for i18n.

@kleinicke You can't use placeholders in yaml. They are inserted as is and won't be filled with variable values.

**Comment by kleinicke** [comment] 2023-01-25 23:06
I solved this by updating the small text yml file on contentful.

**Comment by kleinicke** [comment] 2023-01-25 23:07
I also updated the smalltexts.yml file on GitHub, but it's not used anyways.

**Comment by janosh** [comment] 2023-01-26 00:06
@kleinicke Thanks! [Fix confirmed](https://studenten-bilden-schueler.de/standorte/kiel). Didn't realize the file on GitHub isn't used. How about we delete it then?

**Closed by janosh** 2023-01-26 00:06 UTC
Labels: bug

**Comment by dominikgeissler** [comment] 2023-01-26 10:01
@janosh iirc it is kept to copy-paste it for other website languages. But I agree that it is a bit confusing.
